/* Generated by Yosys 0.51+46 (git sha1 8bde6ac17, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module APB_Master(SWRITE, SADDR, SWDATA, SSTRB, SPROT, transfer, PSEL, PENABLE, PWRITE, PADDR, PWDATA, PSTRB, PPROT, PCLK, PRESETn, PREADY, PSLVERR);
  wire [31:0] _000_;
  wire [2:0] _001_;
  wire [3:0] _002_;
  wire [31:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  output [31:0] PADDR;
  wire [31:0] PADDR;
  input PCLK;
  wire PCLK;
  output PENABLE;
  wire PENABLE;
  output [2:0] PPROT;
  wire [2:0] PPROT;
  input PREADY;
  wire PREADY;
  input PRESETn;
  wire PRESETn;
  output PSEL;
  wire PSEL;
  input PSLVERR;
  wire PSLVERR;
  output [3:0] PSTRB;
  wire [3:0] PSTRB;
  output [31:0] PWDATA;
  wire [31:0] PWDATA;
  output PWRITE;
  wire PWRITE;
  input [31:0] SADDR;
  wire [31:0] SADDR;
  input [2:0] SPROT;
  wire [2:0] SPROT;
  input [3:0] SSTRB;
  wire [3:0] SSTRB;
  input [31:0] SWDATA;
  wire [31:0] SWDATA;
  input SWRITE;
  wire SWRITE;
  wire [1:0] cs;
  wire [1:0] ns;
  input transfer;
  wire transfer;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _011_ (
    .A(cs[1]),
    .SLEEP(PREADY),
    .X(_005_)
  );
  sky130_fd_sc_hd__nor2_1 _012_ (
    .A(cs[0]),
    .B(_005_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__and2_0 _013_ (
    .A(cs[0]),
    .B(cs[1]),
    .X(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _014_ (
    .A(_006_),
    .B(_007_),
    .Y(ns[1])
  );
  sky130_fd_sc_hd__or3b_1 _015_ (
    .A(cs[0]),
    .B(_005_),
    .C_N(transfer),
    .X(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _016_ (
    .A(_008_),
    .Y(ns[0])
  );
  sky130_fd_sc_hd__mux2_1 _017_ (
    .A0(SPROT[0]),
    .A1(PPROT[0]),
    .S(_008_),
    .X(_001_[0])
  );
  sky130_fd_sc_hd__mux2_1 _018_ (
    .A0(SPROT[1]),
    .A1(PPROT[1]),
    .S(_008_),
    .X(_001_[1])
  );
  sky130_fd_sc_hd__mux2_1 _019_ (
    .A0(SPROT[2]),
    .A1(PPROT[2]),
    .S(_008_),
    .X(_001_[2])
  );
  sky130_fd_sc_hd__mux2_1 _020_ (
    .A0(SSTRB[0]),
    .A1(PSTRB[0]),
    .S(_008_),
    .X(_002_[0])
  );
  sky130_fd_sc_hd__mux2_1 _021_ (
    .A0(SSTRB[1]),
    .A1(PSTRB[1]),
    .S(_008_),
    .X(_002_[1])
  );
  sky130_fd_sc_hd__mux2_1 _022_ (
    .A0(SSTRB[2]),
    .A1(PSTRB[2]),
    .S(_008_),
    .X(_002_[2])
  );
  sky130_fd_sc_hd__mux2_1 _023_ (
    .A0(SSTRB[3]),
    .A1(PSTRB[3]),
    .S(_008_),
    .X(_002_[3])
  );
  sky130_fd_sc_hd__mux2_1 _024_ (
    .A0(SWDATA[0]),
    .A1(PWDATA[0]),
    .S(_008_),
    .X(_003_[0])
  );
  sky130_fd_sc_hd__mux2_1 _025_ (
    .A0(SWDATA[1]),
    .A1(PWDATA[1]),
    .S(_008_),
    .X(_003_[1])
  );
  sky130_fd_sc_hd__mux2_1 _026_ (
    .A0(SWDATA[2]),
    .A1(PWDATA[2]),
    .S(_008_),
    .X(_003_[2])
  );
  sky130_fd_sc_hd__mux2_1 _027_ (
    .A0(SWDATA[3]),
    .A1(PWDATA[3]),
    .S(_008_),
    .X(_003_[3])
  );
  sky130_fd_sc_hd__mux2_1 _028_ (
    .A0(SWDATA[4]),
    .A1(PWDATA[4]),
    .S(_008_),
    .X(_003_[4])
  );
  sky130_fd_sc_hd__mux2_1 _029_ (
    .A0(SWDATA[5]),
    .A1(PWDATA[5]),
    .S(_008_),
    .X(_003_[5])
  );
  sky130_fd_sc_hd__mux2_1 _030_ (
    .A0(SWDATA[6]),
    .A1(PWDATA[6]),
    .S(_008_),
    .X(_003_[6])
  );
  sky130_fd_sc_hd__mux2_1 _031_ (
    .A0(SWDATA[7]),
    .A1(PWDATA[7]),
    .S(_008_),
    .X(_003_[7])
  );
  sky130_fd_sc_hd__mux2_1 _032_ (
    .A0(SWDATA[8]),
    .A1(PWDATA[8]),
    .S(_008_),
    .X(_003_[8])
  );
  sky130_fd_sc_hd__mux2_1 _033_ (
    .A0(SWDATA[9]),
    .A1(PWDATA[9]),
    .S(_008_),
    .X(_003_[9])
  );
  sky130_fd_sc_hd__mux2_1 _034_ (
    .A0(SWDATA[10]),
    .A1(PWDATA[10]),
    .S(_008_),
    .X(_003_[10])
  );
  sky130_fd_sc_hd__mux2_1 _035_ (
    .A0(SWDATA[11]),
    .A1(PWDATA[11]),
    .S(_008_),
    .X(_003_[11])
  );
  sky130_fd_sc_hd__mux2_1 _036_ (
    .A0(SWDATA[12]),
    .A1(PWDATA[12]),
    .S(_008_),
    .X(_003_[12])
  );
  sky130_fd_sc_hd__mux2_1 _037_ (
    .A0(SWDATA[13]),
    .A1(PWDATA[13]),
    .S(_008_),
    .X(_003_[13])
  );
  sky130_fd_sc_hd__mux2_1 _038_ (
    .A0(SWDATA[14]),
    .A1(PWDATA[14]),
    .S(_008_),
    .X(_003_[14])
  );
  sky130_fd_sc_hd__mux2_1 _039_ (
    .A0(SWDATA[15]),
    .A1(PWDATA[15]),
    .S(_008_),
    .X(_003_[15])
  );
  sky130_fd_sc_hd__mux2_1 _040_ (
    .A0(SWDATA[16]),
    .A1(PWDATA[16]),
    .S(_008_),
    .X(_003_[16])
  );
  sky130_fd_sc_hd__mux2_1 _041_ (
    .A0(SWDATA[17]),
    .A1(PWDATA[17]),
    .S(_008_),
    .X(_003_[17])
  );
  sky130_fd_sc_hd__mux2_1 _042_ (
    .A0(SWDATA[18]),
    .A1(PWDATA[18]),
    .S(_008_),
    .X(_003_[18])
  );
  sky130_fd_sc_hd__mux2_1 _043_ (
    .A0(SWDATA[19]),
    .A1(PWDATA[19]),
    .S(_008_),
    .X(_003_[19])
  );
  sky130_fd_sc_hd__mux2_1 _044_ (
    .A0(SWDATA[20]),
    .A1(PWDATA[20]),
    .S(_008_),
    .X(_003_[20])
  );
  sky130_fd_sc_hd__mux2_1 _045_ (
    .A0(SWDATA[21]),
    .A1(PWDATA[21]),
    .S(_008_),
    .X(_003_[21])
  );
  sky130_fd_sc_hd__mux2_1 _046_ (
    .A0(SWDATA[22]),
    .A1(PWDATA[22]),
    .S(_008_),
    .X(_003_[22])
  );
  sky130_fd_sc_hd__mux2_1 _047_ (
    .A0(SWDATA[23]),
    .A1(PWDATA[23]),
    .S(_008_),
    .X(_003_[23])
  );
  sky130_fd_sc_hd__mux2_1 _048_ (
    .A0(SWDATA[24]),
    .A1(PWDATA[24]),
    .S(_008_),
    .X(_003_[24])
  );
  sky130_fd_sc_hd__mux2_1 _049_ (
    .A0(SWDATA[25]),
    .A1(PWDATA[25]),
    .S(_008_),
    .X(_003_[25])
  );
  sky130_fd_sc_hd__mux2_1 _050_ (
    .A0(SWDATA[26]),
    .A1(PWDATA[26]),
    .S(_008_),
    .X(_003_[26])
  );
  sky130_fd_sc_hd__mux2_1 _051_ (
    .A0(SWDATA[27]),
    .A1(PWDATA[27]),
    .S(_008_),
    .X(_003_[27])
  );
  sky130_fd_sc_hd__mux2_1 _052_ (
    .A0(SWDATA[28]),
    .A1(PWDATA[28]),
    .S(_008_),
    .X(_003_[28])
  );
  sky130_fd_sc_hd__mux2_1 _053_ (
    .A0(SWDATA[29]),
    .A1(PWDATA[29]),
    .S(_008_),
    .X(_003_[29])
  );
  sky130_fd_sc_hd__mux2_1 _054_ (
    .A0(SWDATA[30]),
    .A1(PWDATA[30]),
    .S(_008_),
    .X(_003_[30])
  );
  sky130_fd_sc_hd__mux2_1 _055_ (
    .A0(SWDATA[31]),
    .A1(PWDATA[31]),
    .S(_008_),
    .X(_003_[31])
  );
  sky130_fd_sc_hd__mux2_1 _056_ (
    .A0(SADDR[0]),
    .A1(PADDR[0]),
    .S(_008_),
    .X(_000_[0])
  );
  sky130_fd_sc_hd__mux2_1 _057_ (
    .A0(SADDR[1]),
    .A1(PADDR[1]),
    .S(_008_),
    .X(_000_[1])
  );
  sky130_fd_sc_hd__mux2_1 _058_ (
    .A0(SADDR[2]),
    .A1(PADDR[2]),
    .S(_008_),
    .X(_000_[2])
  );
  sky130_fd_sc_hd__mux2_1 _059_ (
    .A0(SADDR[3]),
    .A1(PADDR[3]),
    .S(_008_),
    .X(_000_[3])
  );
  sky130_fd_sc_hd__mux2_1 _060_ (
    .A0(SADDR[4]),
    .A1(PADDR[4]),
    .S(_008_),
    .X(_000_[4])
  );
  sky130_fd_sc_hd__mux2_1 _061_ (
    .A0(SADDR[5]),
    .A1(PADDR[5]),
    .S(_008_),
    .X(_000_[5])
  );
  sky130_fd_sc_hd__mux2_1 _062_ (
    .A0(SADDR[6]),
    .A1(PADDR[6]),
    .S(_008_),
    .X(_000_[6])
  );
  sky130_fd_sc_hd__mux2_1 _063_ (
    .A0(SADDR[7]),
    .A1(PADDR[7]),
    .S(_008_),
    .X(_000_[7])
  );
  sky130_fd_sc_hd__mux2_1 _064_ (
    .A0(SADDR[8]),
    .A1(PADDR[8]),
    .S(_008_),
    .X(_000_[8])
  );
  sky130_fd_sc_hd__mux2_1 _065_ (
    .A0(SADDR[9]),
    .A1(PADDR[9]),
    .S(_008_),
    .X(_000_[9])
  );
  sky130_fd_sc_hd__mux2_1 _066_ (
    .A0(SADDR[10]),
    .A1(PADDR[10]),
    .S(_008_),
    .X(_000_[10])
  );
  sky130_fd_sc_hd__mux2_1 _067_ (
    .A0(SADDR[11]),
    .A1(PADDR[11]),
    .S(_008_),
    .X(_000_[11])
  );
  sky130_fd_sc_hd__mux2_1 _068_ (
    .A0(SADDR[12]),
    .A1(PADDR[12]),
    .S(_008_),
    .X(_000_[12])
  );
  sky130_fd_sc_hd__mux2_1 _069_ (
    .A0(SADDR[13]),
    .A1(PADDR[13]),
    .S(_008_),
    .X(_000_[13])
  );
  sky130_fd_sc_hd__mux2_1 _070_ (
    .A0(SADDR[14]),
    .A1(PADDR[14]),
    .S(_008_),
    .X(_000_[14])
  );
  sky130_fd_sc_hd__mux2_1 _071_ (
    .A0(SADDR[15]),
    .A1(PADDR[15]),
    .S(_008_),
    .X(_000_[15])
  );
  sky130_fd_sc_hd__mux2_1 _072_ (
    .A0(SADDR[16]),
    .A1(PADDR[16]),
    .S(_008_),
    .X(_000_[16])
  );
  sky130_fd_sc_hd__mux2_1 _073_ (
    .A0(SADDR[17]),
    .A1(PADDR[17]),
    .S(_008_),
    .X(_000_[17])
  );
  sky130_fd_sc_hd__mux2_1 _074_ (
    .A0(SADDR[18]),
    .A1(PADDR[18]),
    .S(_008_),
    .X(_000_[18])
  );
  sky130_fd_sc_hd__mux2_1 _075_ (
    .A0(SADDR[19]),
    .A1(PADDR[19]),
    .S(_008_),
    .X(_000_[19])
  );
  sky130_fd_sc_hd__mux2_1 _076_ (
    .A0(SADDR[20]),
    .A1(PADDR[20]),
    .S(_008_),
    .X(_000_[20])
  );
  sky130_fd_sc_hd__mux2_1 _077_ (
    .A0(SADDR[21]),
    .A1(PADDR[21]),
    .S(_008_),
    .X(_000_[21])
  );
  sky130_fd_sc_hd__mux2_1 _078_ (
    .A0(SADDR[22]),
    .A1(PADDR[22]),
    .S(_008_),
    .X(_000_[22])
  );
  sky130_fd_sc_hd__mux2_1 _079_ (
    .A0(SADDR[23]),
    .A1(PADDR[23]),
    .S(_008_),
    .X(_000_[23])
  );
  sky130_fd_sc_hd__mux2_1 _080_ (
    .A0(SADDR[24]),
    .A1(PADDR[24]),
    .S(_008_),
    .X(_000_[24])
  );
  sky130_fd_sc_hd__mux2_1 _081_ (
    .A0(SADDR[25]),
    .A1(PADDR[25]),
    .S(_008_),
    .X(_000_[25])
  );
  sky130_fd_sc_hd__mux2_1 _082_ (
    .A0(SADDR[26]),
    .A1(PADDR[26]),
    .S(_008_),
    .X(_000_[26])
  );
  sky130_fd_sc_hd__mux2_1 _083_ (
    .A0(SADDR[27]),
    .A1(PADDR[27]),
    .S(_008_),
    .X(_000_[27])
  );
  sky130_fd_sc_hd__mux2_1 _084_ (
    .A0(SADDR[28]),
    .A1(PADDR[28]),
    .S(_008_),
    .X(_000_[28])
  );
  sky130_fd_sc_hd__mux2_1 _085_ (
    .A0(SADDR[29]),
    .A1(PADDR[29]),
    .S(_008_),
    .X(_000_[29])
  );
  sky130_fd_sc_hd__mux2_1 _086_ (
    .A0(SADDR[30]),
    .A1(PADDR[30]),
    .S(_008_),
    .X(_000_[30])
  );
  sky130_fd_sc_hd__mux2_1 _087_ (
    .A0(SADDR[31]),
    .A1(PADDR[31]),
    .S(_008_),
    .X(_000_[31])
  );
  sky130_fd_sc_hd__mux2_1 _088_ (
    .A0(SWRITE),
    .A1(PWRITE),
    .S(_008_),
    .X(_004_)
  );
  sky130_fd_sc_hd__o21ai_0 _089_ (
    .A1(_006_),
    .A2(_007_),
    .B1(_008_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _090_ (
    .A(_006_),
    .B(_007_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__dfrtp_1 _091_ (
    .CLK(PCLK),
    .D(_010_),
    .Q(PSEL),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _092_ (
    .CLK(PCLK),
    .D(_009_),
    .Q(PENABLE),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _093_ (
    .CLK(PCLK),
    .D(_004_),
    .Q(PWRITE),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _094_ (
    .CLK(PCLK),
    .D(_000_[0]),
    .Q(PADDR[0]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _095_ (
    .CLK(PCLK),
    .D(_000_[1]),
    .Q(PADDR[1]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _096_ (
    .CLK(PCLK),
    .D(_000_[2]),
    .Q(PADDR[2]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _097_ (
    .CLK(PCLK),
    .D(_000_[3]),
    .Q(PADDR[3]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _098_ (
    .CLK(PCLK),
    .D(_000_[4]),
    .Q(PADDR[4]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _099_ (
    .CLK(PCLK),
    .D(_000_[5]),
    .Q(PADDR[5]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _100_ (
    .CLK(PCLK),
    .D(_000_[6]),
    .Q(PADDR[6]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _101_ (
    .CLK(PCLK),
    .D(_000_[7]),
    .Q(PADDR[7]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _102_ (
    .CLK(PCLK),
    .D(_000_[8]),
    .Q(PADDR[8]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _103_ (
    .CLK(PCLK),
    .D(_000_[9]),
    .Q(PADDR[9]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _104_ (
    .CLK(PCLK),
    .D(_000_[10]),
    .Q(PADDR[10]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _105_ (
    .CLK(PCLK),
    .D(_000_[11]),
    .Q(PADDR[11]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _106_ (
    .CLK(PCLK),
    .D(_000_[12]),
    .Q(PADDR[12]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _107_ (
    .CLK(PCLK),
    .D(_000_[13]),
    .Q(PADDR[13]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _108_ (
    .CLK(PCLK),
    .D(_000_[14]),
    .Q(PADDR[14]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _109_ (
    .CLK(PCLK),
    .D(_000_[15]),
    .Q(PADDR[15]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _110_ (
    .CLK(PCLK),
    .D(_000_[16]),
    .Q(PADDR[16]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _111_ (
    .CLK(PCLK),
    .D(_000_[17]),
    .Q(PADDR[17]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _112_ (
    .CLK(PCLK),
    .D(_000_[18]),
    .Q(PADDR[18]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _113_ (
    .CLK(PCLK),
    .D(_000_[19]),
    .Q(PADDR[19]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _114_ (
    .CLK(PCLK),
    .D(_000_[20]),
    .Q(PADDR[20]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _115_ (
    .CLK(PCLK),
    .D(_000_[21]),
    .Q(PADDR[21]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _116_ (
    .CLK(PCLK),
    .D(_000_[22]),
    .Q(PADDR[22]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _117_ (
    .CLK(PCLK),
    .D(_000_[23]),
    .Q(PADDR[23]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _118_ (
    .CLK(PCLK),
    .D(_000_[24]),
    .Q(PADDR[24]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _119_ (
    .CLK(PCLK),
    .D(_000_[25]),
    .Q(PADDR[25]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _120_ (
    .CLK(PCLK),
    .D(_000_[26]),
    .Q(PADDR[26]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _121_ (
    .CLK(PCLK),
    .D(_000_[27]),
    .Q(PADDR[27]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _122_ (
    .CLK(PCLK),
    .D(_000_[28]),
    .Q(PADDR[28]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _123_ (
    .CLK(PCLK),
    .D(_000_[29]),
    .Q(PADDR[29]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _124_ (
    .CLK(PCLK),
    .D(_000_[30]),
    .Q(PADDR[30]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _125_ (
    .CLK(PCLK),
    .D(_000_[31]),
    .Q(PADDR[31]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _126_ (
    .CLK(PCLK),
    .D(_003_[0]),
    .Q(PWDATA[0]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _127_ (
    .CLK(PCLK),
    .D(_003_[1]),
    .Q(PWDATA[1]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _128_ (
    .CLK(PCLK),
    .D(_003_[2]),
    .Q(PWDATA[2]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _129_ (
    .CLK(PCLK),
    .D(_003_[3]),
    .Q(PWDATA[3]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _130_ (
    .CLK(PCLK),
    .D(_003_[4]),
    .Q(PWDATA[4]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _131_ (
    .CLK(PCLK),
    .D(_003_[5]),
    .Q(PWDATA[5]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _132_ (
    .CLK(PCLK),
    .D(_003_[6]),
    .Q(PWDATA[6]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _133_ (
    .CLK(PCLK),
    .D(_003_[7]),
    .Q(PWDATA[7]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _134_ (
    .CLK(PCLK),
    .D(_003_[8]),
    .Q(PWDATA[8]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _135_ (
    .CLK(PCLK),
    .D(_003_[9]),
    .Q(PWDATA[9]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _136_ (
    .CLK(PCLK),
    .D(_003_[10]),
    .Q(PWDATA[10]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _137_ (
    .CLK(PCLK),
    .D(_003_[11]),
    .Q(PWDATA[11]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _138_ (
    .CLK(PCLK),
    .D(_003_[12]),
    .Q(PWDATA[12]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _139_ (
    .CLK(PCLK),
    .D(_003_[13]),
    .Q(PWDATA[13]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _140_ (
    .CLK(PCLK),
    .D(_003_[14]),
    .Q(PWDATA[14]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _141_ (
    .CLK(PCLK),
    .D(_003_[15]),
    .Q(PWDATA[15]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _142_ (
    .CLK(PCLK),
    .D(_003_[16]),
    .Q(PWDATA[16]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _143_ (
    .CLK(PCLK),
    .D(_003_[17]),
    .Q(PWDATA[17]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _144_ (
    .CLK(PCLK),
    .D(_003_[18]),
    .Q(PWDATA[18]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _145_ (
    .CLK(PCLK),
    .D(_003_[19]),
    .Q(PWDATA[19]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _146_ (
    .CLK(PCLK),
    .D(_003_[20]),
    .Q(PWDATA[20]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _147_ (
    .CLK(PCLK),
    .D(_003_[21]),
    .Q(PWDATA[21]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _148_ (
    .CLK(PCLK),
    .D(_003_[22]),
    .Q(PWDATA[22]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _149_ (
    .CLK(PCLK),
    .D(_003_[23]),
    .Q(PWDATA[23]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _150_ (
    .CLK(PCLK),
    .D(_003_[24]),
    .Q(PWDATA[24]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _151_ (
    .CLK(PCLK),
    .D(_003_[25]),
    .Q(PWDATA[25]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _152_ (
    .CLK(PCLK),
    .D(_003_[26]),
    .Q(PWDATA[26]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _153_ (
    .CLK(PCLK),
    .D(_003_[27]),
    .Q(PWDATA[27]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _154_ (
    .CLK(PCLK),
    .D(_003_[28]),
    .Q(PWDATA[28]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _155_ (
    .CLK(PCLK),
    .D(_003_[29]),
    .Q(PWDATA[29]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _156_ (
    .CLK(PCLK),
    .D(_003_[30]),
    .Q(PWDATA[30]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _157_ (
    .CLK(PCLK),
    .D(_003_[31]),
    .Q(PWDATA[31]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _158_ (
    .CLK(PCLK),
    .D(_002_[0]),
    .Q(PSTRB[0]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _159_ (
    .CLK(PCLK),
    .D(_002_[1]),
    .Q(PSTRB[1]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _160_ (
    .CLK(PCLK),
    .D(_002_[2]),
    .Q(PSTRB[2]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _161_ (
    .CLK(PCLK),
    .D(_002_[3]),
    .Q(PSTRB[3]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _162_ (
    .CLK(PCLK),
    .D(_001_[0]),
    .Q(PPROT[0]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _163_ (
    .CLK(PCLK),
    .D(_001_[1]),
    .Q(PPROT[1]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _164_ (
    .CLK(PCLK),
    .D(_001_[2]),
    .Q(PPROT[2]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _165_ (
    .CLK(PCLK),
    .D(ns[0]),
    .Q(cs[0]),
    .RESET_B(PRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _166_ (
    .CLK(PCLK),
    .D(ns[1]),
    .Q(cs[1]),
    .RESET_B(PRESETn)
  );
endmodule

module APB_Slave_with_SRAM(PSEL, PENABLE, PWRITE, PADDR, PWDATA, PSTRB, PPROT, PCLK, PRESETn, PRDATA, PREADY, PSLVERR);
  wire [31:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  input [31:0] PADDR;
  wire [31:0] PADDR;
  input PCLK;
  wire PCLK;
  input PENABLE;
  wire PENABLE;
  input [2:0] PPROT;
  wire [2:0] PPROT;
  output [31:0] PRDATA;
  wire [31:0] PRDATA;
  output PREADY;
  wire PREADY;
  input PRESETn;
  wire PRESETn;
  input PSEL;
  wire PSEL;
  output PSLVERR;
  wire PSLVERR;
  input [3:0] PSTRB;
  wire [3:0] PSTRB;
  input [31:0] PWDATA;
  wire [31:0] PWDATA;
  input PWRITE;
  wire PWRITE;
  wire [7:0] sram_dout;
  sky130_fd_sc_hd__clkinv_1 _022_ (
    .A(PSEL),
    .Y(_020_)
  );
  sky130_fd_sc_hd__clkinv_1 _023_ (
    .A(PRESETn),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _024_ (
    .A(PRDATA[0]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _025_ (
    .A(PRDATA[1]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _026_ (
    .A(PRDATA[2]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _027_ (
    .A(PRDATA[3]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _028_ (
    .A(PRDATA[4]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _029_ (
    .A(PRDATA[5]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _030_ (
    .A(PRDATA[6]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _031_ (
    .A(PRDATA[7]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__and2_0 _032_ (
    .A(PSEL),
    .B(PENABLE),
    .X(PREADY)
  );
  sky130_fd_sc_hd__nand2b_1 _033_ (
    .A_N(PWRITE),
    .B(PSEL),
    .Y(_016_)
  );
  sky130_fd_sc_hd__and3_1 _034_ (
    .A(PSLVERR),
    .B(PRESETn),
    .C(_016_),
    .X(_001_)
  );
  sky130_fd_sc_hd__nor3b_1 _035_ (
    .A(PWRITE),
    .B(sram_dout[0]),
    .C_N(PSEL),
    .Y(_017_)
  );
  sky130_fd_sc_hd__a211oi_1 _036_ (
    .A1(_008_),
    .A2(_016_),
    .B1(_017_),
    .C1(_007_),
    .Y(_000_[0])
  );
  sky130_fd_sc_hd__nor3b_1 _037_ (
    .A(PWRITE),
    .B(sram_dout[1]),
    .C_N(PSEL),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a211oi_1 _038_ (
    .A1(_009_),
    .A2(_016_),
    .B1(_018_),
    .C1(_007_),
    .Y(_000_[1])
  );
  sky130_fd_sc_hd__nor3b_1 _039_ (
    .A(PWRITE),
    .B(sram_dout[2]),
    .C_N(PSEL),
    .Y(_019_)
  );
  sky130_fd_sc_hd__a211oi_1 _040_ (
    .A1(_010_),
    .A2(_016_),
    .B1(_019_),
    .C1(_007_),
    .Y(_000_[2])
  );
  sky130_fd_sc_hd__nor3b_1 _041_ (
    .A(PWRITE),
    .B(sram_dout[3]),
    .C_N(PSEL),
    .Y(_002_)
  );
  sky130_fd_sc_hd__a211oi_1 _042_ (
    .A1(_011_),
    .A2(_016_),
    .B1(_002_),
    .C1(_007_),
    .Y(_000_[3])
  );
  sky130_fd_sc_hd__nor3b_1 _043_ (
    .A(PWRITE),
    .B(sram_dout[4]),
    .C_N(PSEL),
    .Y(_003_)
  );
  sky130_fd_sc_hd__a211oi_1 _044_ (
    .A1(_012_),
    .A2(_016_),
    .B1(_003_),
    .C1(_007_),
    .Y(_000_[4])
  );
  sky130_fd_sc_hd__nor3b_1 _045_ (
    .A(PWRITE),
    .B(sram_dout[5]),
    .C_N(PSEL),
    .Y(_004_)
  );
  sky130_fd_sc_hd__a211oi_1 _046_ (
    .A1(_013_),
    .A2(_016_),
    .B1(_004_),
    .C1(_007_),
    .Y(_000_[5])
  );
  sky130_fd_sc_hd__nor3b_1 _047_ (
    .A(PWRITE),
    .B(sram_dout[6]),
    .C_N(PSEL),
    .Y(_005_)
  );
  sky130_fd_sc_hd__a211oi_1 _048_ (
    .A1(_014_),
    .A2(_016_),
    .B1(_005_),
    .C1(_007_),
    .Y(_000_[6])
  );
  sky130_fd_sc_hd__nor3b_1 _049_ (
    .A(PWRITE),
    .B(sram_dout[7]),
    .C_N(PSEL),
    .Y(_006_)
  );
  sky130_fd_sc_hd__a211oi_1 _050_ (
    .A1(_015_),
    .A2(_016_),
    .B1(_006_),
    .C1(_007_),
    .Y(_000_[7])
  );
  sky130_fd_sc_hd__and3_1 _051_ (
    .A(PRESETn),
    .B(PRDATA[8]),
    .C(_016_),
    .X(_000_[8])
  );
  sky130_fd_sc_hd__and3_1 _052_ (
    .A(PRESETn),
    .B(PRDATA[9]),
    .C(_016_),
    .X(_000_[9])
  );
  sky130_fd_sc_hd__and3_1 _053_ (
    .A(PRESETn),
    .B(PRDATA[10]),
    .C(_016_),
    .X(_000_[10])
  );
  sky130_fd_sc_hd__and3_1 _054_ (
    .A(PRESETn),
    .B(PRDATA[11]),
    .C(_016_),
    .X(_000_[11])
  );
  sky130_fd_sc_hd__and3_1 _055_ (
    .A(PRESETn),
    .B(PRDATA[12]),
    .C(_016_),
    .X(_000_[12])
  );
  sky130_fd_sc_hd__and3_1 _056_ (
    .A(PRESETn),
    .B(PRDATA[13]),
    .C(_016_),
    .X(_000_[13])
  );
  sky130_fd_sc_hd__and3_1 _057_ (
    .A(PRESETn),
    .B(PRDATA[14]),
    .C(_016_),
    .X(_000_[14])
  );
  sky130_fd_sc_hd__and3_1 _058_ (
    .A(PRESETn),
    .B(PRDATA[15]),
    .C(_016_),
    .X(_000_[15])
  );
  sky130_fd_sc_hd__and3_1 _059_ (
    .A(PRESETn),
    .B(PRDATA[16]),
    .C(_016_),
    .X(_000_[16])
  );
  sky130_fd_sc_hd__and3_1 _060_ (
    .A(PRESETn),
    .B(PRDATA[17]),
    .C(_016_),
    .X(_000_[17])
  );
  sky130_fd_sc_hd__and3_1 _061_ (
    .A(PRESETn),
    .B(PRDATA[18]),
    .C(_016_),
    .X(_000_[18])
  );
  sky130_fd_sc_hd__and3_1 _062_ (
    .A(PRESETn),
    .B(PRDATA[19]),
    .C(_016_),
    .X(_000_[19])
  );
  sky130_fd_sc_hd__and3_1 _063_ (
    .A(PRESETn),
    .B(PRDATA[20]),
    .C(_016_),
    .X(_000_[20])
  );
  sky130_fd_sc_hd__and3_1 _064_ (
    .A(PRESETn),
    .B(PRDATA[21]),
    .C(_016_),
    .X(_000_[21])
  );
  sky130_fd_sc_hd__and3_1 _065_ (
    .A(PRESETn),
    .B(PRDATA[22]),
    .C(_016_),
    .X(_000_[22])
  );
  sky130_fd_sc_hd__and3_1 _066_ (
    .A(PRESETn),
    .B(PRDATA[23]),
    .C(_016_),
    .X(_000_[23])
  );
  sky130_fd_sc_hd__and3_1 _067_ (
    .A(PRESETn),
    .B(PRDATA[24]),
    .C(_016_),
    .X(_000_[24])
  );
  sky130_fd_sc_hd__and3_1 _068_ (
    .A(PRESETn),
    .B(PRDATA[25]),
    .C(_016_),
    .X(_000_[25])
  );
  sky130_fd_sc_hd__and3_1 _069_ (
    .A(PRESETn),
    .B(PRDATA[26]),
    .C(_016_),
    .X(_000_[26])
  );
  sky130_fd_sc_hd__and3_1 _070_ (
    .A(PRESETn),
    .B(PRDATA[27]),
    .C(_016_),
    .X(_000_[27])
  );
  sky130_fd_sc_hd__and3_1 _071_ (
    .A(PRESETn),
    .B(PRDATA[28]),
    .C(_016_),
    .X(_000_[28])
  );
  sky130_fd_sc_hd__and3_1 _072_ (
    .A(PRESETn),
    .B(PRDATA[29]),
    .C(_016_),
    .X(_000_[29])
  );
  sky130_fd_sc_hd__and3_1 _073_ (
    .A(PRESETn),
    .B(PRDATA[30]),
    .C(_016_),
    .X(_000_[30])
  );
  sky130_fd_sc_hd__and3_1 _074_ (
    .A(PRESETn),
    .B(PRDATA[31]),
    .C(_016_),
    .X(_000_[31])
  );
  sky130_fd_sc_hd__nand2_1 _075_ (
    .A(PSEL),
    .B(PWRITE),
    .Y(_021_)
  );
  sky130_fd_sc_hd__dfxtp_1 _076_ (
    .CLK(PCLK),
    .D(_000_[0]),
    .Q(PRDATA[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _077_ (
    .CLK(PCLK),
    .D(_000_[1]),
    .Q(PRDATA[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _078_ (
    .CLK(PCLK),
    .D(_000_[2]),
    .Q(PRDATA[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _079_ (
    .CLK(PCLK),
    .D(_000_[3]),
    .Q(PRDATA[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _080_ (
    .CLK(PCLK),
    .D(_000_[4]),
    .Q(PRDATA[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _081_ (
    .CLK(PCLK),
    .D(_000_[5]),
    .Q(PRDATA[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _082_ (
    .CLK(PCLK),
    .D(_000_[6]),
    .Q(PRDATA[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _083_ (
    .CLK(PCLK),
    .D(_000_[7]),
    .Q(PRDATA[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _084_ (
    .CLK(PCLK),
    .D(_000_[8]),
    .Q(PRDATA[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _085_ (
    .CLK(PCLK),
    .D(_000_[9]),
    .Q(PRDATA[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _086_ (
    .CLK(PCLK),
    .D(_000_[10]),
    .Q(PRDATA[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _087_ (
    .CLK(PCLK),
    .D(_000_[11]),
    .Q(PRDATA[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _088_ (
    .CLK(PCLK),
    .D(_000_[12]),
    .Q(PRDATA[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _089_ (
    .CLK(PCLK),
    .D(_000_[13]),
    .Q(PRDATA[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _090_ (
    .CLK(PCLK),
    .D(_000_[14]),
    .Q(PRDATA[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _091_ (
    .CLK(PCLK),
    .D(_000_[15]),
    .Q(PRDATA[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _092_ (
    .CLK(PCLK),
    .D(_000_[16]),
    .Q(PRDATA[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _093_ (
    .CLK(PCLK),
    .D(_000_[17]),
    .Q(PRDATA[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _094_ (
    .CLK(PCLK),
    .D(_000_[18]),
    .Q(PRDATA[18])
  );
  sky130_fd_sc_hd__dfxtp_1 _095_ (
    .CLK(PCLK),
    .D(_000_[19]),
    .Q(PRDATA[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _096_ (
    .CLK(PCLK),
    .D(_000_[20]),
    .Q(PRDATA[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _097_ (
    .CLK(PCLK),
    .D(_000_[21]),
    .Q(PRDATA[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _098_ (
    .CLK(PCLK),
    .D(_000_[22]),
    .Q(PRDATA[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _099_ (
    .CLK(PCLK),
    .D(_000_[23]),
    .Q(PRDATA[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _100_ (
    .CLK(PCLK),
    .D(_000_[24]),
    .Q(PRDATA[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _101_ (
    .CLK(PCLK),
    .D(_000_[25]),
    .Q(PRDATA[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _102_ (
    .CLK(PCLK),
    .D(_000_[26]),
    .Q(PRDATA[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _103_ (
    .CLK(PCLK),
    .D(_000_[27]),
    .Q(PRDATA[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _104_ (
    .CLK(PCLK),
    .D(_000_[28]),
    .Q(PRDATA[28])
  );
  sky130_fd_sc_hd__dfxtp_1 _105_ (
    .CLK(PCLK),
    .D(_000_[29]),
    .Q(PRDATA[29])
  );
  sky130_fd_sc_hd__dfxtp_1 _106_ (
    .CLK(PCLK),
    .D(_000_[30]),
    .Q(PRDATA[30])
  );
  sky130_fd_sc_hd__dfxtp_1 _107_ (
    .CLK(PCLK),
    .D(_000_[31]),
    .Q(PRDATA[31])
  );
  sky130_fd_sc_hd__dfxtp_1 _108_ (
    .CLK(PCLK),
    .D(_001_),
    .Q(PSLVERR)
  );
  sram_8_256_sky130A u_sram (
    .addr0(PADDR[7:0]),
    .clk0(PCLK),
    .csb0(_020_),
    .din0(PWDATA[7:0]),
    .dout0(sram_dout),
    .gnd(1'h0),
    .vdd(1'h1),
    .web0(_021_)
  );
endmodule

module APB_Wrapper(PCLK, PRESETn, SWRITE, SADDR, SWDATA, SSTRB, SPROT, transfer, PRDATA);
  wire [31:0] PADDR;
  input PCLK;
  wire PCLK;
  wire PENABLE;
  wire [2:0] PPROT;
  output [31:0] PRDATA;
  wire [31:0] PRDATA;
  wire PREADY;
  input PRESETn;
  wire PRESETn;
  wire PSEL;
  wire PSLVERR;
  wire [3:0] PSTRB;
  wire [31:0] PWDATA;
  wire PWRITE;
  input [31:0] SADDR;
  wire [31:0] SADDR;
  input [2:0] SPROT;
  wire [2:0] SPROT;
  input [3:0] SSTRB;
  wire [3:0] SSTRB;
  input [31:0] SWDATA;
  wire [31:0] SWDATA;
  input SWRITE;
  wire SWRITE;
  wire [31:0] prdata_internal;
  input transfer;
  wire transfer;
  APB_Master Master (
    .PADDR(PADDR),
    .PCLK(PCLK),
    .PENABLE(PENABLE),
    .PPROT(PPROT),
    .PREADY(PREADY),
    .PRESETn(PRESETn),
    .PSEL(PSEL),
    .PSLVERR(PSLVERR),
    .PSTRB(PSTRB),
    .PWDATA(PWDATA),
    .PWRITE(PWRITE),
    .SADDR(SADDR),
    .SPROT(SPROT),
    .SSTRB(SSTRB),
    .SWDATA(SWDATA),
    .SWRITE(SWRITE),
    .transfer(transfer)
  );
  APB_Slave_with_SRAM Slave (
    .PADDR(PADDR),
    .PCLK(PCLK),
    .PENABLE(PENABLE),
    .PPROT(PPROT),
    .PRDATA(prdata_internal),
    .PREADY(PREADY),
    .PRESETn(PRESETn),
    .PSEL(PSEL),
    .PSLVERR(PSLVERR),
    .PSTRB(PSTRB),
    .PWDATA(PWDATA),
    .PWRITE(PWRITE)
  );
  assign PRDATA = prdata_internal;
endmodule
